// data.js — Base de datos del Mapa FIUBA (Sede Paseo Colón)

const PISOS = {
  ss: { nombre: "Subsuelo",    svg: "svgs/subsuelo.svg",    orden: 0 },
  pb: { nombre: "Planta Baja", svg: "svgs/planta-baja.svg", orden: 1 },
  p1: { nombre: "1er Piso",    svg: "svgs/piso-1.svg",      orden: 2 },
  p2: { nombre: "2do Piso",    svg: "svgs/piso-2.svg",      orden: 3 },
  p3: { nombre: "3er Piso",    svg: "svgs/piso-3.svg",      orden: 4 },
  p4: { nombre: "4to Piso",    svg: "svgs/piso-4.svg",      orden: 5 },
  p5: { nombre: "5to Piso",    svg: "svgs/piso-5.svg",      orden: 6 },
};

const ESPACIOS = [
  // ─────────────────────────────────────────
  // SUBSUELO
  // ─────────────────────────────────────────
  { svgId: "aula_e1",          nombre: "Aula E1",                              tipo: "aula",        piso: "ss", sector: "Sur-Oeste",   palabrasClave: ["e1","aula e1"] },
  { svgId: "aula_e3",          nombre: "Aula E3",                              tipo: "aula",        piso: "ss", sector: "Sur-Oeste",   palabrasClave: ["e3","aula e3"] },
  { svgId: "aula_e5",          nombre: "Aula E5",                              tipo: "aula",        piso: "ss", sector: "Ala Oeste",   palabrasClave: ["e5","aula e5"] },
  { svgId: "aula_e7",          nombre: "Aula E7",                              tipo: "aula",        piso: "ss", sector: "Centro-Oeste",palabrasClave: ["e7","aula e7"] },
  { svgId: "aula_e8",          nombre: "Aula E8 — Lab Electrónica y Robótica", tipo: "laboratorio", piso: "ss", sector: "Sur-Este",    palabrasClave: ["e8","aula e8","electronica","robotica","isep"] },
  { svgId: "aula_e9",          nombre: "Aula E9",                              tipo: "aula",        piso: "ss", sector: "Sur-Centro",  palabrasClave: ["e9","aula e9"] },
  { svgId: "aula_e10",         nombre: "Aula E10",                             tipo: "aula",        piso: "ss", sector: "Sur-Este",    palabrasClave: ["e10","aula e10"] },
  { svgId: "aula_e14",         nombre: "Aula E14",                             tipo: "aula",        piso: "ss", sector: "Centro-Este", palabrasClave: ["e14","aula e14"] },
  { svgId: "aula_e16",         nombre: "Aula E16",                             tipo: "aula",        piso: "ss", sector: "Centro-Este", palabrasClave: ["e16","aula e16"] },
  { svgId: "aula_e29",         nombre: "Aula E29",                             tipo: "aula",        piso: "ss", sector: "Centro-Oeste",palabrasClave: ["e29","aula e29"] },
  { svgId: "aula_e32",         nombre: "Aula E32",                             tipo: "aula",        piso: "ss", sector: "Norte-Centro",palabrasClave: ["e32","aula e32"] },
  { svgId: "aula_e33",         nombre: "Aula E33",                             tipo: "aula",        piso: "ss", sector: "Norte-Este",  palabrasClave: ["e33","aula e33"] },
  { svgId: "comedor",         nombre: "Comedor",                              tipo: "comedor",     piso: "ss", sector: "Ala Este",    palabrasClave: ["comedor","buffet","comer","almorzar","comida","cafeteria"] },
  { svgId: "comedor-docente", nombre: "Comedor Docente",                      tipo: "comedor",     piso: "ss", sector: "Sur-Este",    palabrasClave: ["comedor docente","buffet","docentes"] },
  { svgId: "lab-ablacion",    nombre: "Lab de Ablación Láser",                tipo: "laboratorio", piso: "ss", sector: "Norte-Oeste", palabrasClave: ["ablacion","laser","laboratorio","lab ablacion"] },
  { svgId: "lab-solidos",     nombre: "Lab de Sólidos Amorfos",               tipo: "laboratorio", piso: "ss", sector: "Ala Oeste",   palabrasClave: ["solidos","amorfos","laboratorio"] },
  { svgId: "taller-mecanica", nombre: "Taller de Mecánica de Enseñanza",      tipo: "laboratorio", piso: "ss", sector: "Norte-Centro",palabrasClave: ["taller","mecanica","enseñanza","taller mecanica"] },
  { svgId: "isep",            nombre: "ISEP",                                  tipo: "otro",        piso: "ss", sector: "Sur-Este",    palabrasClave: ["isep"] },
  { svgId: "bano-damas-ss",   nombre: "Baño Damas — Subsuelo",                tipo: "bano",        piso: "ss", sector: "Norte-Centro",palabrasClave: ["baño","damas","mujeres","sanitario","subsuelo","ss"] },
  { svgId: "bano-hombres-ss", nombre: "Baño Hombres — Subsuelo",              tipo: "bano",        piso: "ss", sector: "Norte-Centro",palabrasClave: ["baño","hombres","caballeros","sanitario","subsuelo","ss"] },
  { svgId: "sala-sueno",      nombre: "Sala del Sueño / Nursery",             tipo: "otro",        piso: "ss", sector: "Ala Oeste",   palabrasClave: ["nursery","sala del sueño","jardin maternal","maternal","guarderia"] },
  { svgId: "sala-comp-ss",    nombre: "Sala Computación / Gabinete Becarios", tipo: "otro",        piso: "ss", sector: "Sur-Este",    palabrasClave: ["sala de computacion","becarios","pasantes","gabinete"] },
  { svgId: "mecanica-aplicada",nombre: "Mecánica Aplicada",                   tipo: "laboratorio", piso: "ss", sector: "Centro-Este", palabrasClave: ["mecanica aplicada","lab mecanica","fluido","combustion"] },

  // ─────────────────────────────────────────
  // PLANTA BAJA
  // ─────────────────────────────────────────
  { svgId: "entrada",            nombre: "Entrada / Salida Principal",          tipo: "otro",     piso: "pb", sector: "Sur-Centro",  palabrasClave: ["entrada","salida","acceso","ingreso","porteria","hall central"] },
  { svgId: "salon-polideportivo",nombre: "Salón Polideportivo",                 tipo: "otro",     piso: "pb", sector: "Norte-Centro",palabrasClave: ["polideportivo","salon","deporte","deportivo","gimnasio","salon polideportivo"] },
  { svgId: "salon-actos",        nombre: "Salón de Actos",                      tipo: "otro",     piso: "pb", sector: "Centro-Oeste",palabrasClave: ["salon de actos","actos","auditorio","conferencias","eventos"] },
  { svgId: "mesa-entradas",      nombre: "Mesa de Entradas",                    tipo: "tramites", piso: "pb", sector: "Centro-Este", palabrasClave: ["mesa de entradas","entradas","tramites","notas","certificado","constancia","expediente"] },
  { svgId: "mesa-proyecto-ing",  nombre: "Mesa de Proyecto de Ingeniería",      tipo: "especial", piso: "pb", sector: "Centro",      palabrasClave: ["mesa de proyecto","proyecto ingenieria","mesa proyecto","pi","proyecto final","tp final"] },
  { svgId: "admision",           nombre: "Admisión / Dep. de Alumnos",          tipo: "tramites", piso: "pb", sector: "Centro-Este", palabrasClave: ["admision","alumnos","departamento alumnos","inscripcion","ingresantes","reincorporacion"] },
  { svgId: "sec-academica",      nombre: "Secretaría Académica",                tipo: "tramites", piso: "pb", sector: "Sur-Este",    palabrasClave: ["secretaria academica","secretaria","academica","tramites","equivalencias"] },
  { svgId: "direcc-academica",   nombre: "Dirección Académica",                 tipo: "tramites", piso: "pb", sector: "Sur-Este",    palabrasClave: ["direccion academica","direccion","academica"] },
  { svgId: "decano",             nombre: "Oficina del Decano",                  tipo: "tramites", piso: "pb", sector: "Centro-Oeste",palabrasClave: ["decano","decanato","oficina decano"] },
  { svgId: "vice-decano",        nombre: "Vice Decanato",                       tipo: "tramites", piso: "pb", sector: "Sur-Oeste",   palabrasClave: ["vice","vicedecanato","vice decano"] },
  { svgId: "sec-administrativa", nombre: "Secretaría Administrativa",           tipo: "tramites", piso: "pb", sector: "Sur-Centro",  palabrasClave: ["secretaria administrativa","administrativa"] },
  { svgId: "consejeria",         nombre: "Consejería Estudiantil",              tipo: "tramites", piso: "pb", sector: "Centro",      palabrasClave: ["consejeria","estudiantil","consejo estudiantil"] },
  { svgId: "comunic-univ",       nombre: "Comunicación Universitaria",          tipo: "tramites", piso: "pb", sector: "Ala Este",    palabrasClave: ["comunicacion","universitaria","prensa","difusion"] },
  { svgId: "tesoreria",          nombre: "Tesorería",                           tipo: "tramites", piso: "pb", sector: "Sur-Este",    palabrasClave: ["tesoreria","pagos","aranceles","tesoreria"] },
  { svgId: "dir-contable",       nombre: "Dirección Principal Contable",        tipo: "tramites", piso: "pb", sector: "Sur-Centro",  palabrasClave: ["contable","direccion contable","contabilidad"] },
  { svgId: "bano-damas-pb",      nombre: "Baño Damas — Planta Baja",            tipo: "bano",     piso: "pb", sector: "Centro-Oeste",palabrasClave: ["baño","damas","mujeres","sanitario","planta baja","pb"] },
  { svgId: "bano-caballeros-pb", nombre: "Baño Caballeros — Planta Baja",       tipo: "bano",     piso: "pb", sector: "Centro-Este", palabrasClave: ["baño","hombres","caballeros","sanitario","planta baja","pb"] },
  { svgId: "duchas",             nombre: "Duchas",                              tipo: "bano",     piso: "pb", sector: "Norte-Este",  palabrasClave: ["duchas","ducha","vestuario"] },
  { svgId: "eudeba-seuba",       nombre: "EUDEBA / SEUBA",                      tipo: "otro",     piso: "pb", sector: "Centro",      palabrasClave: ["eudeba","seuba","libreria","libros","editorial"] },
  { svgId: "fotocopiadora",      nombre: "Fotocopiadora",                       tipo: "otro",     piso: "pb", sector: "Centro-Este", palabrasClave: ["fotocopiadora","fotocopias","copias","impresiones","fotocopia"] },
  { svgId: "bicicletero",        nombre: "Bicicletero",                         tipo: "otro",     piso: "pb", sector: "Sur-Centro",  palabrasClave: ["bicicletero","bici","bicicleta"] },
  { svgId: "cei",                nombre: "CEI — Centro de Estudiantes",         tipo: "otro",     piso: "pb", sector: "Norte-Oeste", palabrasClave: ["cei","centro estudiantes","agrupacion","centro de estudiantes"] },
  { svgId: "sala-pc-pb",         nombre: "Sala de PC",                          tipo: "otro",     piso: "pb", sector: "Norte-Oeste", palabrasClave: ["sala pc","computadoras","sala de computacion"] },
  { svgId: "dpto-deporte",       nombre: "DPTO Deporte",                        tipo: "tramites", piso: "pb", sector: "Centro-Este", palabrasClave: ["deporte","deportes","depto deporte","actividad fisica"] },
  { svgId: "dir-personal",       nombre: "Dirección de Personal",               tipo: "tramites", piso: "pb", sector: "Norte-Este",  palabrasClave: ["personal","recursos humanos","direccion personal","rrhh"] },
  { svgId: "sec-posgrado-pb",    nombre: "Secretaría de Posgrado",              tipo: "tramites", piso: "pb", sector: "Ala Oeste",   palabrasClave: ["posgrado","maestria","doctorado","postgrado","secretaria posgrado"] },

  // ─────────────────────────────────────────
  // PISO 1
  // ─────────────────────────────────────────
  { svgId: "aula-103",         nombre: "Aula 103",                          tipo: "aula",        piso: "p1", sector: "Centro",       palabrasClave: ["103","aula 103"] },
  { svgId: "aula-105",         nombre: "Aula 105",                          tipo: "aula",        piso: "p1", sector: "Centro-Oeste", palabrasClave: ["105","aula 105"] },
  { svgId: "aula-107",         nombre: "Aula 107",                          tipo: "aula",        piso: "p1", sector: "Ala Oeste",    palabrasClave: ["107","aula 107"] },
  { svgId: "aula-l1",          nombre: "Aula L1",                           tipo: "aula",        piso: "p1", sector: "Sur-Este",     palabrasClave: ["l1","aula l1"] },
  { svgId: "aula-l2",          nombre: "Aula L2",                           tipo: "aula",        piso: "p1", sector: "Sur-Este",     palabrasClave: ["l2","aula l2"] },
  { svgId: "aula-l3",          nombre: "Aula L3",                           tipo: "aula",        piso: "p1", sector: "Sur-Este",     palabrasClave: ["l3","aula l3"] },
  { svgId: "aula-l5",          nombre: "Aula L5",                           tipo: "aula",        piso: "p1", sector: "Ala Este",     palabrasClave: ["l5","aula l5"] },
  { svgId: "aula-l6",          nombre: "Aula L6",                           tipo: "aula",        piso: "p1", sector: "Ala Este",     palabrasClave: ["l6","aula l6"] },
  { svgId: "aula-l7",          nombre: "Aula L7",                           tipo: "aula",        piso: "p1", sector: "Ala Este",     palabrasClave: ["l7","aula l7"] },
  { svgId: "aula-l9",          nombre: "Aula L9",                           tipo: "aula",        piso: "p1", sector: "Ala Este",     palabrasClave: ["l9","aula l9"] },
  { svgId: "aula-l10",         nombre: "Aula L10",                          tipo: "aula",        piso: "p1", sector: "Norte-Este",   palabrasClave: ["l10","aula l10"] },
  { svgId: "aula-l11",         nombre: "Aula L11",                          tipo: "aula",        piso: "p1", sector: "Norte-Este",   palabrasClave: ["l11","aula l11"] },
  { svgId: "aula-l13",         nombre: "Aula L13",                          tipo: "aula",        piso: "p1", sector: "Norte-Este",   palabrasClave: ["l13","aula l13"] },
  { svgId: "aula-l14",         nombre: "Aula L14",                          tipo: "aula",        piso: "p1", sector: "Centro-Este",  palabrasClave: ["l14","aula l14"] },
  { svgId: "lab-compu-p1",     nombre: "Lab de Computación",                tipo: "laboratorio", piso: "p1", sector: "Ala Oeste",    palabrasClave: ["lab computacion","computacion","computadoras","laboratorio"] },
  { svgId: "dpto-matematica",  nombre: "DPTO Matemática",                   tipo: "tramites",    piso: "p1", sector: "Ala Oeste",    palabrasClave: ["matematica","dpto matematica","departamento matematica","calculo"] },
  { svgId: "espacio-estudio",  nombre: "Espacio de Estudio",                tipo: "otro",        piso: "p1", sector: "Centro",       palabrasClave: ["espacio de estudio","estudio","sala estudio","estudiar"] },
  { svgId: "biblioteca-p1",    nombre: "Biblioteca (1er Piso)",             tipo: "biblioteca",  piso: "p1", sector: "Centro-Este",  palabrasClave: ["biblioteca","libros","prestar","1er piso"] },
  { svgId: "labi",             nombre: "LABI",                              tipo: "laboratorio", piso: "p1", sector: "Centro-Este",  palabrasClave: ["labi","laboratorio integrado"] },
  { svgId: "bano-damas-p1",    nombre: "Baño Damas — 1er Piso",             tipo: "bano",        piso: "p1", sector: "Centro-Oeste", palabrasClave: ["baño","damas","mujeres","1er piso","p1"] },
  { svgId: "bano-hombres-p1",  nombre: "Baño Hombres — 1er Piso",           tipo: "bano",        piso: "p1", sector: "Norte-Este",   palabrasClave: ["baño","hombres","caballeros","1er piso","p1"] },
  { svgId: "sec-extension",    nombre: "Sec. de Extensión Universitaria",   tipo: "tramites",    piso: "p1", sector: "Centro-Oeste", palabrasClave: ["extension","universitaria","secretaria extension"] },
  { svgId: "sucor",            nombre: "S.U.C.O.R.",                        tipo: "otro",        piso: "p1", sector: "Norte-Este",   palabrasClave: ["sucor","radio","comunicacion universitaria"] },
  { svgId: "lab-circuitos",    nombre: "Lab de Circuitos Impresos",         tipo: "laboratorio", piso: "p1", sector: "Norte-Este",   palabrasClave: ["circuitos","circuitos impresos","laboratorio","pcb"] },
  { svgId: "lab-instrumentos", nombre: "Lab Instrumentos y Mediciones",     tipo: "laboratorio", piso: "p1", sector: "Norte-Este",   palabrasClave: ["instrumentos","mediciones","laboratorio","panol"] },
  { svgId: "dpto-electronica", nombre: "DPTO Electrónica",                  tipo: "tramites",    piso: "p1", sector: "Sur-Este",     palabrasClave: ["electronica","dpto electronica","departamento electronica"] },
  { svgId: "lab-acustico",     nombre: "Lab Acústico",                      tipo: "laboratorio", piso: "p1", sector: "Sur-Este",     palabrasClave: ["acustico","acustica","laboratorio acustico"] },
  { svgId: "labcatif",         nombre: "LABCATIF",                          tipo: "laboratorio", piso: "p1", sector: "Norte-Centro",  palabrasClave: ["labcatif","laboratorio"] },
  { svgId: "lae",              nombre: "LAE",                               tipo: "laboratorio", piso: "p1", sector: "Norte-Centro",  palabrasClave: ["lae","laboratorio"] },

  // ─────────────────────────────────────────
  // PISO 2
  // ─────────────────────────────────────────
  { svgId: "aula-200",          nombre: "Aula 200",                    tipo: "aula",        piso: "p2", sector: "Sur-Centro",  palabrasClave: ["200","aula 200"] },
  { svgId: "aula-201",          nombre: "Aula 201",                    tipo: "aula",        piso: "p2", sector: "Ala Oeste",   palabrasClave: ["201","aula 201"] },
  { svgId: "aula-202",          nombre: "Aula 202",                    tipo: "aula",        piso: "p2", sector: "Ala Este",    palabrasClave: ["202","aula 202"] },
  { svgId: "aula-203",          nombre: "Aula 203",                    tipo: "aula",        piso: "p2", sector: "Sur-Oeste",   palabrasClave: ["203","aula 203"] },
  { svgId: "aula-221",          nombre: "Aula 221",                    tipo: "aula",        piso: "p2", sector: "Norte-Centro",palabrasClave: ["221","aula 221"] },
  { svgId: "aula-222",          nombre: "Aula 222",                    tipo: "aula",        piso: "p2", sector: "Norte-Centro",palabrasClave: ["222","aula 222"] },
  { svgId: "aula-237",          nombre: "Aula 237",                    tipo: "aula",        piso: "p2", sector: "Centro-Oeste",palabrasClave: ["237","aula 237"] },
  { svgId: "aula-211a",         nombre: "Aula 211A",                   tipo: "aula",        piso: "p2", sector: "Norte-Este",  palabrasClave: ["211a","aula 211a","211 a"] },
  { svgId: "aula-211b",         nombre: "Aula 211B",                   tipo: "aula",        piso: "p2", sector: "Norte-Este",  palabrasClave: ["211b","aula 211b","211 b"] },
  { svgId: "aula-211c",         nombre: "Aula 211C",                   tipo: "aula",        piso: "p2", sector: "Norte-Este",  palabrasClave: ["211c","aula 211c","211 c"] },
  { svgId: "lab-fisica-1",      nombre: "Lab de Física I",             tipo: "laboratorio", piso: "p2", sector: "Ala Este",    palabrasClave: ["fisica 1","fisica i","laboratorio fisica","lab fisica"] },
  { svgId: "lab-fisica-2",      nombre: "Lab de Física II",            tipo: "laboratorio", piso: "p2", sector: "Ala Oeste",   palabrasClave: ["fisica 2","fisica ii","laboratorio fisica"] },
  { svgId: "lab-fisica-3",      nombre: "Lab de Física III",           tipo: "laboratorio", piso: "p2", sector: "Sur-Oeste",   palabrasClave: ["fisica 3","fisica iii","laboratorio fisica"] },
  { svgId: "lab-laser-p2",      nombre: "Lab de Láser",                tipo: "laboratorio", piso: "p2", sector: "Centro",      palabrasClave: ["laser","laboratorio laser"] },
  { svgId: "lab-electro-optica",nombre: "Lab Electro-Óptica",          tipo: "laboratorio", piso: "p2", sector: "Centro-Este", palabrasClave: ["electro optica","optica","laboratorio optica"] },
  { svgId: "lab-mec-comp",      nombre: "Lab Mecánica Computacional",  tipo: "laboratorio", piso: "p2", sector: "Ala Este",    palabrasClave: ["mecanica computacional","lab mecanica","computacional"] },
  { svgId: "dpto-fisica",       nombre: "DPTO Física",                 tipo: "tramites",    piso: "p2", sector: "Norte-Este",  palabrasClave: ["fisica","dpto fisica","departamento fisica"] },
  { svgId: "bano-damas-p2",     nombre: "Baño Damas — 2do Piso",       tipo: "bano",        piso: "p2", sector: "Centro-Oeste",palabrasClave: ["baño","damas","mujeres","2do piso","p2"] },
  { svgId: "bano-hombres-p2",   nombre: "Baño Hombres — 2do Piso",     tipo: "bano",        piso: "p2", sector: "Norte-Centro",palabrasClave: ["baño","hombres","caballeros","2do piso","p2"] },
  { svgId: "microscopio",       nombre: "Lab Microscopio Electrónico", tipo: "laboratorio", piso: "p2", sector: "Sur-Oeste",   palabrasClave: ["microscopio","electronico","laboratorio"] },
  { svgId: "lab-peliculas",     nombre: "Lab Películas Delgadas",      tipo: "laboratorio", piso: "p2", sector: "Sur-Este",    palabrasClave: ["peliculas delgadas","laboratorio"] },
  { svgId: "lab-sist-liquidos", nombre: "Lab Sistemas Líquidos",       tipo: "laboratorio", piso: "p2", sector: "Norte-Este",  palabrasClave: ["sistemas liquidos","laboratorio"] },

  // ─────────────────────────────────────────
  // PISO 3
  // ─────────────────────────────────────────
  { svgId: "biblioteca-3",      nombre: "Biblioteca Central",              tipo: "biblioteca", piso: "p3", sector: "Norte",        palabrasClave: ["biblioteca","libros","prestar","estudio","biblioteca central"] },
  { svgId: "sala-parlante",     nombre: "Sala Parlante — Biblioteca",      tipo: "biblioteca", piso: "p3", sector: "Ala Oeste",    palabrasClave: ["sala parlante","parlante","biblioteca","hablar","trabajar en grupo"] },
  { svgId: "sala-silenciosa",   nombre: "Sala Silenciosa — Biblioteca",    tipo: "biblioteca", piso: "p3", sector: "Norte-Centro", palabrasClave: ["sala silenciosa","silenciosa","biblioteca","estudiar","silencio"] },
  { svgId: "recep-biblioteca",  nombre: "Recepción Biblioteca",            tipo: "biblioteca", piso: "p3", sector: "Centro",       palabrasClave: ["recepcion biblioteca","biblioteca","prestar libros","devolver"] },
  { svgId: "videoteca",         nombre: "Videoteca",                       tipo: "biblioteca", piso: "p3", sector: "Norte-Este",   palabrasClave: ["videoteca","videos","biblioteca","multimedia"] },
  { svgId: "publicaciones",     nombre: "Publicaciones",                   tipo: "otro",       piso: "p3", sector: "Norte-Oeste",  palabrasClave: ["publicaciones","revistas","diario"] },
  { svgId: "aula-301",          nombre: "Aula 301",                        tipo: "aula",       piso: "p3", sector: "Centro-Oeste", palabrasClave: ["301","aula 301"] },
  { svgId: "aula-302",          nombre: "Aula 302",                        tipo: "aula",       piso: "p3", sector: "Ala Este",     palabrasClave: ["302","aula 302"] },
  { svgId: "aula-303",          nombre: "Aula 303",                        tipo: "aula",       piso: "p3", sector: "Ala Oeste",    palabrasClave: ["303","aula 303"] },
  { svgId: "aula-304",          nombre: "Aula 304",                        tipo: "aula",       piso: "p3", sector: "Sur-Este",     palabrasClave: ["304","aula 304"] },
  { svgId: "aula-305",          nombre: "Aula 305",                        tipo: "aula",       piso: "p3", sector: "Ala Oeste",    palabrasClave: ["305","aula 305"] },
  { svgId: "aula-310",          nombre: "Aula 310",                        tipo: "aula",       piso: "p3", sector: "Sur-Este",     palabrasClave: ["310","aula 310"] },
  { svgId: "aula-313",          nombre: "Aula 313",                        tipo: "aula",       piso: "p3", sector: "Sur-Oeste",    palabrasClave: ["313","aula 313"] },
  { svgId: "aula-319",          nombre: "Aula 319",                        tipo: "aula",       piso: "p3", sector: "Sur-Centro",   palabrasClave: ["319","aula 319"] },
  { svgId: "bano-damas-p3",     nombre: "Baño Damas — 3er Piso",           tipo: "bano",       piso: "p3", sector: "Centro-Oeste", palabrasClave: ["baño","damas","mujeres","3er piso","p3"] },
  { svgId: "bano-hombres-p3",   nombre: "Baño Hombres — 3er Piso",         tipo: "bano",       piso: "p3", sector: "Centro-Este",  palabrasClave: ["baño","hombres","caballeros","3er piso","p3"] },
  { svgId: "serv-hig-seg",      nombre: "Serv. Higiene y Seguridad",       tipo: "tramites",   piso: "p3", sector: "Sur-Centro",   palabrasClave: ["higiene","seguridad","ays","servicio higiene"] },
  { svgId: "sec-empresarial",   nombre: "Secretaría Empresarial",          tipo: "tramites",   piso: "p3", sector: "Sur-Este",     palabrasClave: ["empresarial","secretaria empresarial","pasantias","trabajo","empleo"] },
  { svgId: "graduados-telecom", nombre: "Graduados Telecom",               tipo: "otro",       piso: "p3", sector: "Sur-Oeste",    palabrasClave: ["graduados","telecom","graduados telecom","egresados"] },
  { svgId: "dir-biblioteca",    nombre: "Dirección de Biblioteca",         tipo: "tramites",   piso: "p3", sector: "Norte-Este",   palabrasClave: ["direccion biblioteca","director biblioteca"] },

  // ─────────────────────────────────────────
  // PISO 4
  // ─────────────────────────────────────────
  { svgId: "aula-400",          nombre: "Aula 400",                         tipo: "aula",        piso: "p4", sector: "Sur-Centro",  palabrasClave: ["400","aula 400"] },
  { svgId: "aula-401",          nombre: "Aula 401",                         tipo: "aula",        piso: "p4", sector: "Centro-Oeste",palabrasClave: ["401","aula 401"] },
  { svgId: "aula-402",          nombre: "Aula 402",                         tipo: "aula",        piso: "p4", sector: "Centro-Este", palabrasClave: ["402","aula 402"] },
  { svgId: "aula-403",          nombre: "Aula 403",                         tipo: "aula",        piso: "p4", sector: "Ala Oeste",   palabrasClave: ["403","aula 403"] },
  { svgId: "aula-405",          nombre: "Aula 405",                         tipo: "aula",        piso: "p4", sector: "Ala Oeste",   palabrasClave: ["405","aula 405"] },
  { svgId: "aula-407",          nombre: "Aula 407",                         tipo: "aula",        piso: "p4", sector: "Centro-Oeste",palabrasClave: ["407","aula 407"] },
  { svgId: "aula-408",          nombre: "Aula 408",                         tipo: "aula",        piso: "p4", sector: "Sur-Centro",  palabrasClave: ["408","aula 408"] },
  { svgId: "aula-411",          nombre: "Aula 411",                         tipo: "aula",        piso: "p4", sector: "Sur-Oeste",   palabrasClave: ["411","aula 411"] },
  { svgId: "aula-412",          nombre: "Aula 412",                         tipo: "aula",        piso: "p4", sector: "Sur-Este",    palabrasClave: ["412","aula 412"] },
  { svgId: "aula-414",          nombre: "Aula 414",                         tipo: "aula",        piso: "p4", sector: "Sur-Este",    palabrasClave: ["414","aula 414"] },
  { svgId: "aula-416",          nombre: "Aula 416",                         tipo: "aula",        piso: "p4", sector: "Sur-Este",    palabrasClave: ["416","aula 416"] },
  { svgId: "aula-417",          nombre: "Aula 417",                         tipo: "aula",        piso: "p4", sector: "Centro",      palabrasClave: ["417","aula 417"] },
  { svgId: "aula-422",          nombre: "Aula 422",                         tipo: "aula",        piso: "p4", sector: "Centro",      palabrasClave: ["422","aula 422"] },
  { svgId: "aula-430",          nombre: "Aula 430",                         tipo: "aula",        piso: "p4", sector: "Centro-Este", palabrasClave: ["430","aula 430"] },
  { svgId: "bederia",           nombre: "Bedería",                          tipo: "tramites",    piso: "p4", sector: "Ala Oeste",   palabrasClave: ["bederia","bedería","constancias","tramites","materias","libretas","regularidades"] },
  { svgId: "dpto-sanitaria",    nombre: "DPTO Ing. Sanitaria",              tipo: "tramites",    piso: "p4", sector: "Ala Oeste",   palabrasClave: ["sanitaria","ing sanitaria","departamento sanitaria"] },
  { svgId: "dpto-naval",        nombre: "DPTO Naval",                       tipo: "tramites",    piso: "p4", sector: "Sur-Este",    palabrasClave: ["naval","dpto naval","departamento naval","ing naval"] },
  { svgId: "dpto-compu-p4",     nombre: "DPTO Computación",                 tipo: "tramites",    piso: "p4", sector: "Ala Este",    palabrasClave: ["computacion","sistemas","dpto computacion","departamento computacion"] },
  { svgId: "sala-mainframe",    nombre: "Sala del Main Frame",              tipo: "otro",        piso: "p4", sector: "Ala Este",    palabrasClave: ["mainframe","main frame","sala","servidores"] },
  { svgId: "sala-pc-p4",        nombre: "Sala PC",                          tipo: "otro",        piso: "p4", sector: "Ala Este",    palabrasClave: ["sala pc","computadoras","sala de computacion"] },
  { svgId: "bano-damas-p4",     nombre: "Baño Damas — 4to Piso",            tipo: "bano",        piso: "p4", sector: "Centro-Oeste",palabrasClave: ["baño","damas","mujeres","4to piso","p4"] },
  { svgId: "bano-hombres-p4",   nombre: "Baño Hombres — 4to Piso",          tipo: "bano",        piso: "p4", sector: "Centro-Este", palabrasClave: ["baño","hombres","caballeros","4to piso","p4"] },
  { svgId: "lab-medios-porosos",nombre: "Lab Medios Porosos",               tipo: "laboratorio", piso: "p4", sector: "Norte-Oeste", palabrasClave: ["medios porosos","laboratorio","porosos"] },
  { svgId: "sec-informat-p4",   nombre: "Secretaría Informática",           tipo: "tramites",    piso: "p4", sector: "Centro",      palabrasClave: ["informatica","secretaria informatica","sistemas informacion"] },
  { svgId: "comunic-intercambios",nombre:"Comunicaciones e Intercambios",   tipo: "tramites",    piso: "p4", sector: "Centro-Este", palabrasClave: ["comunicaciones","intercambios","intercambios academicos","convenios"] },
  { svgId: "inst-biomedica-p4", nombre: "Inst. Ing. Biomédica",             tipo: "laboratorio", piso: "p4", sector: "Ala Oeste",   palabrasClave: ["biomedica","biomedico","ing biomedica","instituto biomedica"] },

  // ─────────────────────────────────────────
  // PISO 5
  // ─────────────────────────────────────────
  { svgId: "aula-500",          nombre: "Aula 500",                          tipo: "aula",        piso: "p5", sector: "Sur-Centro",  palabrasClave: ["500","aula 500"] },
  { svgId: "aula-501",          nombre: "Aula 501",                          tipo: "aula",        piso: "p5", sector: "Norte-Centro", palabrasClave: ["501","aula 501"] },
  { svgId: "aula-502",          nombre: "Aula 502",                          tipo: "aula",        piso: "p5", sector: "Norte-Centro", palabrasClave: ["502","aula 502"] },
  { svgId: "aula-503",          nombre: "Aula 503",                          tipo: "aula",        piso: "p5", sector: "Ala Oeste",    palabrasClave: ["503","aula 503"] },
  { svgId: "aula-504",          nombre: "Aula 504",                          tipo: "aula",        piso: "p5", sector: "Ala Este",     palabrasClave: ["504","aula 504"] },
  { svgId: "aula-505",          nombre: "Aula 505",                          tipo: "aula",        piso: "p5", sector: "Sur-Oeste",    palabrasClave: ["505","aula 505"] },
  { svgId: "aula-506",          nombre: "Aula 506",                          tipo: "aula",        piso: "p5", sector: "Sur-Centro",   palabrasClave: ["506","aula 506"] },
  { svgId: "aula-507",          nombre: "Aula 507",                          tipo: "aula",        piso: "p5", sector: "Sur-Oeste",    palabrasClave: ["507","aula 507"] },
  { svgId: "aula-509",          nombre: "Aula 509",                          tipo: "aula",        piso: "p5", sector: "Sur-Oeste",    palabrasClave: ["509","aula 509"] },
  { svgId: "aula-510",          nombre: "Aula 510",                          tipo: "aula",        piso: "p5", sector: "Sur-Centro",   palabrasClave: ["510","aula 510"] },
  { svgId: "aula-512",          nombre: "Aula 512",                          tipo: "aula",        piso: "p5", sector: "Sur-Este",     palabrasClave: ["512","aula 512"] },
  { svgId: "quimica-organica",  nombre: "Química Orgánica",                  tipo: "laboratorio", piso: "p5", sector: "Norte-Oeste",  palabrasClave: ["quimica organica","organica","quimica"] },
  { svgId: "quimica-analitica", nombre: "Química Analítica",                 tipo: "laboratorio", piso: "p5", sector: "Norte-Este",   palabrasClave: ["quimica analitica","analitica","quimica"] },
  { svgId: "fisiloquimica",     nombre: "Fisilo-Química de Mat. Cerámicos",  tipo: "laboratorio", piso: "p5", sector: "Centro-Oeste", palabrasClave: ["fisiloquimica","ceramicos","materiales","laboratorio ceramica"] },
  { svgId: "quim-heterogeneos", nombre: "Química Sistemas Heterogéneos",     tipo: "laboratorio", piso: "p5", sector: "Ala Este",     palabrasClave: ["heterogeneos","quimica sistemas","quimica"] },
  { svgId: "quim-aplicada",     nombre: "Química y Química Aplicada",        tipo: "laboratorio", piso: "p5", sector: "Ala Este",     palabrasClave: ["quimica aplicada","aplicada","quimica"] },
  { svgId: "dpto-quimica",      nombre: "DPTO Química",                      tipo: "tramites",    piso: "p5", sector: "Ala Este",     palabrasClave: ["dpto quimica","departamento quimica","quimica"] },
  { svgId: "lab-quimica-gral",  nombre: "Lab Química General",               tipo: "laboratorio", piso: "p5", sector: "Sur-Oeste",    palabrasClave: ["quimica general","lab quimica","laboratorio quimica","qgoe","qgi"] },
  { svgId: "inst-biomedica-p5", nombre: "Instituto Ing. Biomédica",          tipo: "laboratorio", piso: "p5", sector: "Centro-Este",  palabrasClave: ["biomedica","biomedico","ing biomedica","bioingenieria"] },
  { svgId: "ceconcei",          nombre: "CECONCEI",                          tipo: "otro",        piso: "p5", sector: "Centro",       palabrasClave: ["ceconcei","centro","conocimiento"] },
  { svgId: "bano-damas-p5",     nombre: "Baño Damas — 5to Piso",             tipo: "bano",        piso: "p5", sector: "Centro",       palabrasClave: ["baño","damas","mujeres","5to piso","p5"] },
  { svgId: "bano-hombres-p5",   nombre: "Baño Hombres — 5to Piso",           tipo: "bano",        piso: "p5", sector: "Centro",       palabrasClave: ["baño","hombres","caballeros","5to piso","p5"] },
];

// ─────────────────────────────────────────
// FILTROS RÁPIDOS
// tipo/tipos debe coincidir con campo 'tipo' de ESPACIOS
// ─────────────────────────────────────────
const FILTROS_RAPIDOS = {
  banos:          { label: "🚻 Baños",           tipo:  "bano"      },
  comedor:        { label: "🍽️ Comedor",          tipo:  "comedor"   },
  biblioteca:     { label: "📚 Biblioteca",       tipo:  "biblioteca"},
  tramites:       { label: "📋 Trámites",         tipo:  "tramites"  },
  "mesa-proyecto":{ label: "⚙️ Mesa de Proyecto", tipo:  "especial"  },
};
